// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB3aeeUTqk4zr2UmT-QGNsVi8U-Z5USIQ',
    appId: '1:502374392525:android:565c1deda6ccb3f9a2ff84',
    messagingSenderId: '502374392525',
    projectId: 'safelight-4ca77',
    storageBucket: 'safelight-4ca77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYWNqSlNEXMh29UdRohOIyr714_RCxD4U',
    appId: '1:502374392525:ios:2a941ab9e561b68ba2ff84',
    messagingSenderId: '502374392525',
    projectId: 'safelight-4ca77',
    storageBucket: 'safelight-4ca77.firebasestorage.app',
    androidClientId: '502374392525-8jdari7ht81ht2dgf10nu640bq5p2ad2.apps.googleusercontent.com',
    iosClientId: '502374392525-l6045c27lkhpeh6821gnmgst7kqb6dfe.apps.googleusercontent.com',
    iosBundleId: 'com.wcl.safelight',
  );
}
